---
# MonoRepo multi services

version: "3.8"
services:
  service01:
    image: ${REGISTRY_URI}app01:${IMAGE_TAG:-latest}
    build:
      context: ./app01/
      dockerfile: Dockerfile
      args:
        JAR_FILE: app.jar
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: ".5"
        reservations:
          memory: 128MB
          cpus: "0.25"
    environment:
      JAVA_OPTS: -XX:+PrintFlagsFinal

  service02:
    image: ${REGISTRY_URI}app02:${IMAGE_TAG:-latest}
    build:
      context: ./app02/
      dockerfile: Dockerfile
      args:
        JAR_FILE: app.jar
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: ".5"
        reservations:
          memory: 128MB
          cpus: "0.25"
    environment:
      JAVA_OPTS: -XX:+PrintFlagsFinal
